#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AppHance.AppExample.Droid.Resource", IsApplication=true)]

namespace AppHance.AppExample.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int background_color = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int background_primary = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int background_secondary = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int emphasize_color = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int green = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int outline_color = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int text_primary = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int text_secondary = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int transparent = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int white = 2130968585;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int apphance_actionbar_bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int apphance_actionbar_bg2 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int apphance_actionbar_done = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int apphance_actionbar_logo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int apphance_actionbar_send = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int apphance_avatar = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int apphance_btn_disabled = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int apphance_btn_focused = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int apphance_btn_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int apphance_btn_pressed = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int apphance_button = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int apphance_button_highlight = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int apphance_dot = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int apphance_eraser = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int apphance_eraser_focused = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int apphance_eraser_normal = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int apphance_eraser_pressed = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int apphance_gallery_bg = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int apphance_gallery_image_bg = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int apphance_gallery_img = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int apphance_gallery_img_focused = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int apphance_gallery_img_normal = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int apphance_gallery_img_pressed = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int apphance_gallery_next = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int apphance_green_button = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int apphance_green_button_normal = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int apphance_green_button_pressed = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int apphance_header = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int apphance_ic_warn = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int apphance_icon = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int apphance_logo = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int apphance_pencil = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int apphance_pencil_focused = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int apphance_pencil_normal = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int apphance_pencil_pressed = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int apphance_report_bg = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int apphance_report_new = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int apphance_spray = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int apphance_spray_focused = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int apphance_spray_normal = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int apphance_spray_pressed = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int apphance_textbox = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int apphance_textbox_focused = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int apphance_textbox_normal = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int apphance_tool_pen = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int apphance_tool_spray = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int apphance_users_list_item_background_selector = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int highlight = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int Icon = 2130837552;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int MyButton = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int clear_overlay = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int edit_overlay = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int login_anon_login_button = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int login_appIdText = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int login_app_version = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int login_application_inactive = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int login_emailText = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int login_failed = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int login_identifyProgress = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int login_loginButton = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int login_login_button = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int login_passwordText = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int login_progress = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int login_quickLoginHint = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int login_quickLoginHint2 = 2131034128;
			
			// aapt resource value: 0x7f050011
			public const int login_skipButton = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int login_title = 2131034130;
			
			// aapt resource value: 0x7f050013
			public const int login_too_many_devices = 2131034131;
			
			// aapt resource value: 0x7f050014
			public const int login_versionNameText = 2131034132;
			
			// aapt resource value: 0x7f050015
			public const int login_versionNumberText = 2131034133;
			
			// aapt resource value: 0x7f050016
			public const int login_welcomeText = 2131034134;
			
			// aapt resource value: 0x7f050017
			public const int login_wrong_application = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int login_wrong_credentials = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int notification_text_login = 2131034137;
			
			// aapt resource value: 0x7f05001a
			public const int notification_text_prelogin = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int notification_text_report = 2131034139;
			
			// aapt resource value: 0x7f05001c
			public const int notification_ticker = 2131034140;
			
			// aapt resource value: 0x7f05001d
			public const int notification_title = 2131034141;
			
			// aapt resource value: 0x7f05001e
			public const int notification_update_text = 2131034142;
			
			// aapt resource value: 0x7f05001f
			public const int notification_update_ticker = 2131034143;
			
			// aapt resource value: 0x7f050020
			public const int notification_update_title = 2131034144;
			
			// aapt resource value: 0x7f050021
			public const int problem_back = 2131034145;
			
			// aapt resource value: 0x7f050022
			public const int problem_cancel = 2131034146;
			
			// aapt resource value: 0x7f050023
			public const int problem_hint = 2131034147;
			
			// aapt resource value: 0x7f050024
			public const int problem_includes = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int problem_includes_comment = 2131034149;
			
			// aapt resource value: 0x7f050026
			public const int problem_includes_logs = 2131034150;
			
			// aapt resource value: 0x7f050027
			public const int problem_includes_screen = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int problem_includes_screenshots_logs_comments = 2131034152;
			
			// aapt resource value: 0x7f050029
			public const int problem_instruction = 2131034153;
			
			// aapt resource value: 0x7f05002a
			public const int problem_postscriptum = 2131034154;
			
			// aapt resource value: 0x7f05002b
			public const int problem_proceed = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int problem_prompt = 2131034156;
			
			// aapt resource value: 0x7f05002d
			public const int problem_report = 2131034157;
			
			// aapt resource value: 0x7f05002e
			public const int problem_select_app = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int problem_title = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int problem_toast_no_message = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int settings_credentials = 2131034161;
			
			// aapt resource value: 0x7f050032
			public const int settings_credentials_email = 2131034162;
			
			// aapt resource value: 0x7f050033
			public const int settings_credentials_email_summary = 2131034163;
			
			// aapt resource value: 0x7f050034
			public const int settings_credentials_password = 2131034164;
			
			// aapt resource value: 0x7f050035
			public const int settings_credentials_password_summary = 2131034165;
			
			// aapt resource value: 0x7f050036
			public const int settings_enabled = 2131034166;
			
			// aapt resource value: 0x7f050037
			public const int settings_enabled_summary = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int settings_menu_start_service = 2131034168;
			
			// aapt resource value: 0x7f050039
			public const int test_api_key = 2131034169;
			
			// aapt resource value: 0x7f05003a
			public const int test_cycles_hint = 2131034170;
			
			// aapt resource value: 0x7f05003b
			public const int test_cycles_manual = 2131034171;
			
			// aapt resource value: 0x7f05003c
			public const int test_cycles_title = 2131034172;
			
			// aapt resource value: 0x7f05003d
			public const int test_ui_group = 2131034173;
			
			// aapt resource value: 0x7f05003e
			public const int test_ui_level = 2131034174;
			
			// aapt resource value: 0x7f05003f
			public const int test_ui_message_hint = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int test_ui_report = 2131034176;
			
			// aapt resource value: 0x7f050041
			public const int test_ui_type = 2131034177;
			
			// aapt resource value: 0x7f050042
			public const int toast_application_blocked = 2131034178;
			
			// aapt resource value: 0x7f050043
			public const int toast_application_inactive = 2131034179;
			
			// aapt resource value: 0x7f050044
			public const int toast_email_changed = 2131034180;
			
			// aapt resource value: 0x7f050045
			public const int toast_enabled_off = 2131034181;
			
			// aapt resource value: 0x7f050046
			public const int toast_enabled_on = 2131034182;
			
			// aapt resource value: 0x7f050047
			public const int toast_first_run = 2131034183;
			
			// aapt resource value: 0x7f050048
			public const int toast_impending_login = 2131034184;
			
			// aapt resource value: 0x7f050049
			public const int toast_mandatory_update = 2131034185;
			
			// aapt resource value: 0x7f05004a
			public const int toast_no_test_cycle_found = 2131034186;
			
			// aapt resource value: 0x7f05004b
			public const int toast_recommended_update = 2131034187;
			
			// aapt resource value: 0x7f05004c
			public const int toast_test_cycle_auto_selected = 2131034188;
			
			// aapt resource value: 0x7f05004d
			public const int toast_too_many_devices = 2131034189;
			
			// aapt resource value: 0x7f05004e
			public const int toast_unknown_mandatory_update = 2131034190;
			
			// aapt resource value: 0x7f05004f
			public const int toast_unknown_recommended_update = 2131034191;
			
			// aapt resource value: 0x7f050050
			public const int toast_wrong_application = 2131034192;
			
			// aapt resource value: 0x7f050051
			public const int toast_wrong_credentials = 2131034193;
			
			// aapt resource value: 0x7f050052
			public const int ui_back = 2131034194;
			
			// aapt resource value: 0x7f050053
			public const int ui_cancel = 2131034195;
			
			// aapt resource value: 0x7f050054
			public const int ui_exit = 2131034196;
			
			// aapt resource value: 0x7f050055
			public const int ui_next = 2131034197;
			
			// aapt resource value: 0x7f050056
			public const int ui_skip = 2131034198;
			
			// aapt resource value: 0x7f050057
			public const int update_changelog = 2131034199;
			
			// aapt resource value: 0x7f050058
			public const int update_close_btn = 2131034200;
			
			// aapt resource value: 0x7f050059
			public const int update_intro = 2131034201;
			
			// aapt resource value: 0x7f05005a
			public const int update_link = 2131034202;
			
			// aapt resource value: 0x7f05005b
			public const int update_perform_btn = 2131034203;
			
			// aapt resource value: 0x7f05005c
			public const int update_required_title = 2131034204;
			
			// aapt resource value: 0x7f05005d
			public const int update_skip_btn = 2131034205;
			
			// aapt resource value: 0x7f05005e
			public const int update_title = 2131034206;
			
			// aapt resource value: 0x7f05005f
			public const int update_version = 2131034207;
			
			// aapt resource value: 0x7f050060
			public const int update_warning_mandatory = 2131034208;
			
			// aapt resource value: 0x7f050061
			public const int update_warning_recommended = 2131034209;
			
			// aapt resource value: 0x7f050062
			public const int view_flip_interval = 2131034210;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
